version: '3.7'

services:
  api:
    container_name: boilerplate-api
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - redis
      - postgres
  redis:
    image : redis:6
    container_name: boilerplate-redis
    command:
      - "redis-server"
      - "--requirepass ${REDIS_PASSWORD}"
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
  postgres:
    container_name: boilerplate-postgres
    image: postgres:13
    networks:
      - app-network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    container_name: boilerplate-mongodb
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
      MONGO_INITDB_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - ./scripts/mongodb/init-mongodb-container.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    ports:
      - ${DB_PORT}:27017
    networks:
      - app-network
  rabbitmq:
    container_name: boilerplate-rabbitmq
    image: rabbitmq:3.9-management
    command: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - app-network
networks:
  app-network:
volumes:
  pgdata: {}
